### ISSUE TITLE
Security Hash verification failed

### ISSUE THREAD

**Issue by gbaso** [ONLYOFFICE/onlyoffice-alfresco#126]
Reopening #40 because I have the same problem.

When I open a file with the option "Edit in ONLYOFFICE" request param `cb_key` is set to a certain value, but when I close the file, after a few seconds I see a new execution of the callback with a different value for `cb_key`. `hash` is the first value, `queryHash` is the second value, therefore a `SecurityException` is thrown. The file is updated, but the lock is not removed.

Tried with firefox, chromium and chromium-based edge.
Tried with both latest release and compiling develop branch.

Alfresco version 7.0.0 (community)
Document server version 6.4.2 (community)
OS: CentOS 7.9

**Comment by aleksandrfedorov97** [comment]
Hi [gbaso](https://github.com/gbaso), can you try to reproduce this bag on [v.7.0.0](https://github.com/ONLYOFFICE/onlyoffice-alfresco/releases/tag/v7.0.0) or provide a more detailed scenario to reproduce this issue?
