### ISSUE TITLE
Impossible to use Share with 5.1 version in ACS 6.2

### ISSUE THREAD

**Issue by jberthoux** [ONLYOFFICE/onlyoffice-alfresco#140]
Hello, 

We are using ACS 6.2.2 and after deploying the latest release (5.1) of the plugin, Share is completely unusable. We have some error logs with the **IsEditableMimetype** evaluator and after some debug, the issue seems to be linked to the [OnlyofficeSettings webscript](https://github.com/ONLYOFFICE/onlyoffice-alfresco/blob/master/repo/src/main/java/com/parashift/onlyoffice/OnlyofficeSettings.java#L30).
Indeed, the values of the `supportedFormats` property are not correctly parsed into String which is causing the Share evaluator errors.
Is it possible to have a fix for this issue?

Regards,
Julien

**Comment by alexanderonlyoffice** [comment]
Hello @jberthoux, thanks for the provided information. We were able to reproduce the issue and fixed it, so the solution will be provided within the next version of the connector for Alfresco. We are testing it right now, but I cannot specify any times frames.

**Comment by jberthoux** [comment]
Hello @alexanderonlyoffice 
Thanks for the quick fix, hope the new release will be available soon ;-)

Regards
