### ISSUE TITLE
Does this work with ACS 7.2?

### ISSUE THREAD

**Issue by seacaspian** [ONLYOFFICE/onlyoffice-alfresco#148]
Hi, I had this onlyoffice integration working with ACS 7.1, but I can't seem to get it to work with 7.2 When I put in the necessary information in the plugin, I get "Authorization Error"

**Comment by aborroy** [comment]
Are you sure that error is not coming from ACS itself?
It looks like a configuration problem related with the Communication Mode between Alfresco and SOLR.
From ACS 7.2, only "secret" and "https" are allowed, "none" has been deprecated.

**Comment by aleksandrfedorov97** [comment]
Could you please specify if the problem recurs?

**Comment by aleksandrfedorov97** [comment]
This issue was closed due to no response.
