### ISSUE TITLE
Encoding Problems?

### ISSUE THREAD

**Issue by heretech373** [ONLYOFFICE/onlyoffice-alfresco#16]
Hey, we are having a very strange issue after installation (which was just by the book).
Alfresco host is Ubuntu Server 16.04 LTS, Documents Server installed on CentOS 7. 
Seems like all OK, except the encoding. And the plugin configuration is just impossible. Any ideas?

![photo_2019-10-31_12-41-10](https://user-images.githubusercontent.com/35836547/67940495-75d85700-fbdc-11e9-81ff-e760ade6b4b8.jpg)

**Comment by Eloncase** [comment]
Hi! It is a known issue with all non-ASCII symbols. It will be fixed in next release

**Comment by LazyGatto** [comment]
BTW all is OK in Alfresco Community 6.1.2-ga.
But the same encoding problem seems to be with Alfresco Community 5.2

**Comment by Eloncase** [comment]
Working fine after fix on both versions
`6.1.2 (r589dc49b-b205)`
`5.2.0 (re21f2be5-b22)`
