### ISSUE TITLE
bug "Consumer View": Consumers cannot view files copied through webdav

### ISSUE THREAD

**Issue by hongminh6123** [ONLYOFFICE/onlyoffice-alfresco#174]
1/Create 2 users, A and B

2/Use user A, create folder "A-Folder", use webdav interface (you can use Webdrive or Windows build-in Webdav mapping) , copy an Excel file into it 

3/Use user A, assign user B as "Consumer" to "A-Folder" 

4/Make sure you have not used user A or any other user to pre-view the Excel file using OnlyOffice, since OnlyOffice will cache the file, and you will not see the problem

5/Use user B, pre-view the Excel file using OnlyOffice --> preview screen will be dumped

**Comment by aleksandrfedorov97** [comment]
Hi [hongminh6123](https://github.com/hongminh6123), can you please specify alfresco version and onlyoffice connector version?

**Comment by hongminh6123** [comment]
Alfresco: should be 6.x (201911-4, Bitnami packaged Community Version)
OnlyOffice: I just updated to the latest but the bug remains

**Comment by aleksandrfedorov97** [comment]
Looking at your screenshot, you are still using version onlyoffice-integration-share-jar-4.2.0. Please update onlioffice-integration-repo and onlyoffice-itegration-share to latest version 6.0.1.
https://github.com/ONLYOFFICE/onlyoffice-alfresco/releases/tag/v6.0.1
![image](https://user-images.githubusercontent.com/62958171/202379742-7361e661-d581-4f80-b8ce-da90277417f9.png)

**Comment by hongminh6123** [comment]
not really, we have two Alfresco instances, I used the un-updated one to take screenshot since the one with the latest update still have the same error

**Comment by aleksandrfedorov97** [comment]
Can you reproduce this scenario again and provide me with the logs `/tomcat/logs/alfresco.log` and `/tomcat/share.log`?

**Comment by aleksandrfedorov97** [comment]
[hongminh6123](https://github.com/hongminh6123), thank you for your submission. We were able to reproduce this issue and will be fixing it.

**Comment by hongminh6123** [comment]
Thanks Fedorov, I was going to post the log but you should already have it by now.

**Comment by hongminh6123** [comment]
Any chance you could merge this to the Master and have new release now ? As I see releases are 5,6 months away (too long) while your issues list is somewhat empty
