### ISSUE TITLE
"Edit in OnlyOffice" button does not create new version

### ISSUE THREAD

**Issue by hongminh6123** [ONLYOFFICE/onlyoffice-alfresco#179]
When in Multi-edit mode, clicking "Edit in OnlyOffice" will open an edit windows, but the new content will be saved to the document's current version, in another word, OnlyOffice will "overwrite" current version instead of creating a new version of the document

**Comment by aleksandrfedorov97** [comment]
Hi [hongminh6123](https://github.com/hongminh6123), Could you provide more details on how to reproduce this error? Ideally a step by step scenario. Also please specify user roles.

**Comment by hongminh6123** [comment]
Sorry my mistake, this behavior happened months ago but with current version that does not happen anymore when I try to recreate it.  May you delete this issue ?
