### ISSUE TITLE
lang messages fr,es,de ANSI & create new error

### ISSUE THREAD

**Issue by jmoest** [ONLYOFFICE/onlyoffice-alfresco#18]
Hello,

Messages files (fr,es,de) in share and in repo are in ansi encoding.
I have error message when I create new document and when I edit txt file.
![image](https://user-images.githubusercontent.com/20969770/69141063-2c38a900-0ac4-11ea-9e92-8619dda4a6ef.png)
Thank you
Jonathan

**Comment by Eloncase** [comment]
Hi. I was able to reproduce an issue. Working on a fix
