### ISSUE TITLE
The Web Script /share/service/components/onlyoffice-edit has responded with a status of 500 - Internal Error.

### ISSUE THREAD

**Issue by fansd0107** [ONLYOFFICE/onlyoffice-alfresco#181]
When I use the jar package compiled from the source code, the following error will appear in the new document. What is the reason? thanks.

`

The Web Script /share/service/components/onlyoffice-edit has responded with a status of 500 - Internal Error.
--

The Web Script [/share/service/components/onlyoffice-edit] has responded with a status of 500 - Internal Error.

500 Description:	An error inside the HTTP server which prevented it from fulfilling the request.
 
Message:	00010006 Failed to execute script 'classpath*:alfresco/site-webscripts/com/parashift/onlyoffice-edit.get.js': 00010005 TypeError: Cannot parse XML: Scanner State 24 not Recognized (jar:file:/usr/local/tomcat/webapps/share/WEB-INF/lib/onlyoffice-integration-share.jar!/alfresco/site-webscripts/com/parashift/onlyoffice-edit.get.js#27(eval)#1)
Server:	Spring WebScripts - v8.32.0 schema 1,000
Time:	2023年1月1日 下午2:51:40
 
Diagnostics:	[Inspect Web Script (com/parashift/onlyoffice-edit.get)]`

**Comment by aleksandrfedorov97** [comment]
Hi [fansd0107](https://github.com/fansd0107), I understand correctly that you are trying to connect a non-release version. If so, please clarify from which branch you are compiling the jar. If not, please indicate the version of alfresco and the version of the connector.

**Comment by aleksandrfedorov97** [comment]
This issue was closed due to no response.
