### ISSUE TITLE
Compile step of Docker Install fails with Maven Error

### ISSUE THREAD

**Issue by IainDelaney** [ONLYOFFICE/onlyoffice-alfresco#189]
I'm trying to install the Docker image of onlyoffice-alfresco on Debian 11 (bullseye) with the 'docker up' command. It's failing for me with the following output:
`bitnami@debian:~/onlyoffice-alfresco$ docker compose up
[+] Running 1/0
 ✔ Container onlyoffice-alfresco-build-1  Created                               0.0s 
Attaching to onlyoffice-alfresco-build-1
onlyoffice-alfresco-build-1  | [INFO] Scanning for projects...
onlyoffice-alfresco-build-1  | Downloading from alfresco-public: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/alfresco-platform-distribution/5.2.g/alfresco-platform-distribution-5.2.g.pom
onlyoffice-alfresco-build-1  | Downloading from alfresco-public-snapshots: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/org/alfresco/alfresco-platform-distribution/5.2.g/alfresco-platform-distribution-5.2.g.pom
onlyoffice-alfresco-build-1  | Downloading from alfresco-private-repository: https://artifacts.alfresco.com/nexus/content/groups/private/org/alfresco/alfresco-platform-distribution/5.2.g/alfresco-platform-distribution-5.2.g.pom
onlyoffice-alfresco-build-1  | Downloading from central: https://repo.maven.apache.org/maven2/org/alfresco/alfresco-platform-distribution/5.2.g/alfresco-platform-distribution-5.2.g.pom
onlyoffice-alfresco-build-1  | [ERROR] [ERROR] Some problems were encountered while processing the POMs:
onlyoffice-alfresco-build-1  | [ERROR] Non-resolvable import POM: Could not transfer artifact org.alfresco:alfresco-platform-distribution:pom:5.2.g from/to alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public): Transfer failed for https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/alfresco-platform-distribution/5.2.g/alfresco-platform-distribution-5.2.g.pom @ line 61, column 25
onlyoffice-alfresco-build-1  | [ERROR] 'dependencies.dependency.version' for org.alfresco:alfresco-repository:jar is missing. @ line 46, column 21
onlyoffice-alfresco-build-1  |  @ 
onlyoffice-alfresco-build-1  | [ERROR] The build could not read 1 project -> [Help 1]
onlyoffice-alfresco-build-1  | [ERROR]   
onlyoffice-alfresco-build-1  | [ERROR]   The project com.onlyoffice.alfresco:onlyoffice-integration:6.1.0 (/onlyoffice-alfresco/pom.xml) has 2 errors
onlyoffice-alfresco-build-1  | [ERROR]     Non-resolvable import POM: Could not transfer artifact org.alfresco:alfresco-platform-distribution:pom:5.2.g from/to alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public): Transfer failed for https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/alfresco-platform-distribution/5.2.g/alfresco-platform-distribution-5.2.g.pom @ line 61, column 25: Unknown host artifacts.alfresco.com: Name or service not known -> [Help 2]
onlyoffice-alfresco-build-1  | [ERROR]     'dependencies.dependency.version' for org.alfresco:alfresco-repository:jar is missing. @ line 46, column 21
onlyoffice-alfresco-build-1  | [ERROR] 
onlyoffice-alfresco-build-1  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
onlyoffice-alfresco-build-1  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
onlyoffice-alfresco-build-1  | [ERROR] 
onlyoffice-alfresco-build-1  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
onlyoffice-alfresco-build-1  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
onlyoffice-alfresco-build-1  | [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
onlyoffice-alfresco-build-1 exited with code 1`

Is there something I can do to fix this or is it a problem with your Docker Compose file?

**Comment by aleksandrfedorov97** [comment]
Hi [IainDelaney](https://github.com/IainDelaney), our docker file is outdated and will be removed soon. See [Installing ONLYOFFICE Alfresco module package](https://github.com/ONLYOFFICE/onlyoffice-alfresco?tab=readme-ov-file#installing-onlyoffice-alfresco-module-package).
