### ISSUE TITLE
Compatibility with ONLYOFFICE Docs 7.5

### ISSUE THREAD

**Issue by jberthoux** [ONLYOFFICE/onlyoffice-alfresco#190]
Hello,

No really an issue, but just a question, is the module will be compatible with ONLYOFFICE Docs 7.5?
Thanks in advance for your reply.

Regards,
Julien

**Comment by AFaust** [comment]
@jberthoux I am currently setting up an ACS 7.4 with OnlyOffice 7.5, and so far it works relatively well. The only issue I had was with an internal programming error that comes up when I miss configuring a specific property (see https://github.com/ONLYOFFICE/onlyoffice-alfresco/issues/182#issuecomment-1793784353)

**Comment by jberthoux** [comment]
Hello @AFaust,

thanks for you reply.

Regards,
Julien
