### ISSUE TITLE
issue with Alfresco 23.1 and 23.2

### ISSUE THREAD

**Issue by giorgiomaddaloni89** [ONLYOFFICE/onlyoffice-alfresco#203]
Hi, 
we installed the latest amps from master branch (6.1.0) in alfresco 23.1 and 23.2. We have this issue:

![image](https://github.com/ONLYOFFICE/onlyoffice-alfresco/assets/34450420/9c67bc55-1da7-4b5f-94a7-7587ab42c7bc)

Everything works with Alfresco 7.4 but there's no solution with newer versions of Alfresco.
Does Anybody have the same problem? Is there a solution? 

Thank you.

**Comment by aleksandrfedorov97** [comment]
Hi [giorgiomaddaloni89](https://github.com/giorgiomaddaloni89), we are aware of this issue and have already fixed it. The module is now at the testing station. This will be fixed in the next release.

**Comment by aleksandrfedorov97** [comment]
Hi [giorgiomaddaloni89](https://github.com/giorgiomaddaloni89), added compatibility with Alfresco 23 in #209
