### ISSUE TITLE
Compatibility with ONLYOFFICE Docs 8.0

### ISSUE THREAD

**Issue by jberthoux** [ONLYOFFICE/onlyoffice-alfresco#204]
Hello,

No really an issue, but just a question, is the module will be compatible with ONLYOFFICE Docs 8.0?
Thanks in advance for your reply.

Regards,
Julien

**Comment by SergeyKorneyev** [comment]
Hello Julien,
The recently released version 7.0.0 is fully compatible with Docs 8.0. The previous version would also work, but you won't be able to open OFORM documents for form filling.
