### ISSUE TITLE
Convert must make new version, not document.

### ISSUE THREAD

**Issue by sergefedorow** [ONLYOFFICE/onlyoffice-alfresco#25]
Convert to ONLYOFFICE function makes new document on a same folder. It's don't correlate with Alfresco concept. Document is a main content in the Alfresco. It can be represented by a lots of files. For example, document Contract can starts from txt notes, continue living in the docx (a lots of versions files) and finished in the last version as a e-signed pdf file. All of this files will be created under one document as versions.

So, following the concept of Alfresco, Convert to ONLYOFFICE should make new version of the document, not new document.

p.s. forked parashift connector makes conversion without of any question to or any action from user. My opinion it is the best solution for converting old format to xml.

**Comment by gb-123-git** [comment]
+1
