### ISSUE TITLE
Converting documents requires valid certificate

### ISSUE THREAD

**Issue by pielonet** [ONLYOFFICE/onlyoffice-alfresco#27]
Hi,

We're using version 3.0 of the plugin.
Converting .doc documents does not work : the user gets a message saying that conversion was successful but either no documents is created or the created document is empty.

Alfresco logs show certificate errors : certificate of Onlyoffice Documentserver is not accepted.

It should be accepted since :
- "Ignore SSL certificate" option is checked
- "Editing in Onlyoffice" works for .docx documents.

Kind regards,
Thierry

**Comment by Eloncase** [comment]
Hi! Thanks for your contribution.
We'll try to reproduce an issue and fix it with the next release.
