### ISSUE TITLE
Creating new file opens up in same tab

### ISSUE THREAD

**Issue by pielonet** [ONLYOFFICE/onlyoffice-alfresco#28]
Hi,

We tested version 4.0.1 of the plugin yesterday.
It works great and solves a problem with self-signed certificates since we now have the possibility to distinguish between public and inner onlyoffice urls.

Nevertheless, there's now an action menu that enables users to create ooxml documents. When clicking on one of these links (Create Document, sheet or Presentation) it opens up Onlyoffice online editor.

The problem is that the editor opens up in the same browser tab. The only possibility to go back to Alfresco is using the "go back" arrow of the browser. This behaviour is misleading users since, until then, clicking on "Edit in Onlyoffice" opens up a NEW tab. Users are used to close that tab when editing is finished.

**We would like to have an option in plugin configuration to decide whether creating new documents opens up in same tab or in a new tab.**

**The other solution would be to always open documents in the same tab (when editing and when creating) and add a button on the editor to return back to Alfresco.**

Kind regards,
Thierry

**Comment by Eloncase** [comment]
Hi! Thanks for your contribution.
We'll fix it with the next release.
