### ISSUE TITLE
Alfresco Module Packages (AMP) for distribution

### ISSUE THREAD

**Issue by revoker** [ONLYOFFICE/onlyoffice-alfresco#32]
EDIT: my links referred to an outdated version (4.2) of Alfresco. I fixed that.

Hello,

[Alfresco's documentation for version 4.2](https://docs.alfresco.com/4.2/concepts/dev-extensions-packaging-techniques-jar-files.html) stated: 

 _- To deploy these JARs, it is recommended to place them inside one or more AMP files, and deploy them into the share.war file._

and

 _- As mentioned previously, installing these JARs directly into the exploded webapp directory_ structure is not recommended as application servers can overwrite your changes at unpredictable times.

And this is exactly what happened to us: the 2 wars were deleted overnight and my installation was broken (possibly due to a restart and/or another AMP update). Except that we are working with Alfresco 5.2; and the doc for this version states:

_Since the early days of the SDK, AMPs have been the way customizations were packaged. In SDK 3 everything is now packaged as a JAR by default, while the AMPs are still available as an optional assembly. This gives developers much more control over packaging and simple modules can easily be deployed as JARs._

So, I guess this is important to distribute not only raw jars, but AMP (Alfresco Modules Packages) to be installed with alfresco-mmt.jar (the module management too). 

IMHO, the best place to do so would be in the docker file. If you agree, I could try this out and submit a pull request based on [Alfresco AMP doc](https://docs.alfresco.com/5.2/tasks/sdk-using-amps.html).

**Comment by Eloncase** [comment]
Hello, @revoker!
Sure, second deploy option is always great.
Although docker file only runs `mvn install` command so it will require changing `pom.xml` anyways. Feel free to submit a PR. Your contribution will be appreciated.
