### ISSUE TITLE
Forcesaving

### ISSUE THREAD

**Issue by jmoest** [ONLYOFFICE/onlyoffice-alfresco#37]
Hello,
I don't understand ForceSaving.
When user1 edits the document and locks the document on Alfresco. 
User2 joins him and also edits the document and clicks on forcesave.
I have an error message due to the lock on the Alfresco document.
"org.alfresco.service.cmr.repository.ContentIOException: 04270069 Failed to set content property on stream closure:
   node: workspace://SpacesStore/c33c342f-3fb8-4099-b595-2e4089f701a6
   property: {http://www.alfresco.org/model/content/1.0}content
   writer: ContentAccessor[ contentUrl=store://2020/5/27/14/55/91b901b3-7f84-4d3a-a4b1-cd89f7156f9c.bin, mimetype=application/vnd.openxmlformats-officedocument.wordprocessingml.document, size=18973, encoding=UTF-8, locale=fr_FR]
org.alfresco.service.cmr.lock.NodeLockedException..."
It's the normal behaviour?
Why not authorize user forcesave despite the lock?
Thank you
Jonathan

**Comment by jmoest** [comment]
Same behaviour when i put forcesaving type 2 (interval) and changes are made by user 2.

**Comment by Eloncase** [comment]
Hello, looks like a bug. I'll look into it.

**Comment by aleksandrfedorov97** [comment]
https://github.com/ONLYOFFICE/onlyoffice-alfresco/pull/129
