### ISSUE TITLE
ODT document content converted to docs content

### ISSUE THREAD

**Issue by svgta1** [ONLYOFFICE/onlyoffice-alfresco#38]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Connection between Alfresco and onlyOffice document server
Same issue with ods. Same issue with nextcloud

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When editing an odt document with onlyOffice, the content saved in Alfresco is not an odt anymore but a docx content. The file extension in Alfresco don't change, nor the mime/type of the document.

**What is the expected behavior?**
The content must be converted in odt when saved in Alfresco.

**Did this work in previous versions of DocumentServer?**
I don't know

**DocumentServer version:**
5.4.1-39

**Operating System:**
Debian 9

**Browser version:**
Brave 1.9.76

**Comment by svgta1** [comment]
I will install a more recent version of onlyOffice to try to detect where the real problem is. But, it's strange to receive in Alfresco the content of a docx document when it's an odt. The content is send from onlyOffice.

**Comment by Eloncase** [comment]
You can't edit `.odt` since `3.0.0` (there is a convert option). So I would recommend updating your connector.

**Comment by svgta1** [comment]
Yes, I saw that few hours ago. I hope the new version is compatible with Alfresco 5.2... I will test that.
But, it's strange that we can edit .odt in nextcloud without this problem to have a content docx, but not with alfresco.

**Comment by LinneyS** [comment]
Hi @svgta1 
In version [4.3.0](https://github.com/ONLYOFFICE/onlyoffice-alfresco/releases/tag/v4.3.0), we added the ability to open the `odt` format for editing. Turn this on in the settings.

**Comment by RadhoineMabroukCeoVision** [comment]
Hi,
I have the same issue, when I edit ODT files the content saved in Alfresco change the format to DOCX.
@LinneyS  I understand from your last answer that the solution to this issue is to turn on the settings for ODT format settings, but you don't tell the way to process, Can you please tell me the steps to turn the settings on ?
Thank you

**Comment by SergeyKorneyev** [comment]
Hello @RadhoineMabroukCeoVision 
Could you tell us what version of the ONLYOFFICE Connector you currently have installed?

**Comment by RadhoineMabroukCeoVision** [comment]
Hi @SergeyKorneyev,
The version I installed is onlyoffice integration share 4.1.0

**Comment by SergeyKorneyev** [comment]
The feature was implemented in version 4.3.0: https://github.com/onlyoffice/onlyoffice-alfresco/releases. Please update the connector. You should see the following option added to its settings: 
![image_2021-06-10_18-28-34](https://user-images.githubusercontent.com/77327210/121555421-ac628e80-ca1b-11eb-8c29-f6c05bafad8f.png)

**Comment by RadhoineMabroukCeoVision** [comment]
Thank you, @SergeyKorneyev
