### ISSUE TITLE
Document stay blocked when a user is readonly while editing

### ISSUE THREAD

**Issue by svgta1** [ONLYOFFICE/onlyoffice-alfresco#47]
When editing a document when an other user is watching it in readonly mode, the document is not saved in Alfresco.

Method :

- User A as write access
- User B is read only

1. User B open the document
2. User A open the document and make updates
3. User A close then document . The document stay blocked in Alfresco
4. User B close then document.  The document stay blocked in Alfresco

If User A re-open the document, he see the updates. He can do more updates. But, the document stay blocked in Alfresco and no newest version is created.

To unblock the situation : 

1. download the document from onlyoffice.
2. unblock the document in alfresco
3. upload the document
4. deleting onlyoffice:editing-hash in the node

OO log same as in issue : [#42](https://github.com/ONLYOFFICE/onlyoffice-alfresco/issues/42)

best regards

**Comment by Eloncase** [comment]
Hi. This is a DocumentServer issue and will be fixed in 5.5.4

**Comment by LinneyS** [comment]
https://github.com/ONLYOFFICE/DocumentServer/issues/914
