### ISSUE TITLE
Issue #47 can be solved

### ISSUE THREAD

**Issue by svgta1** [ONLYOFFICE/onlyoffice-alfresco#48]
I don't know how to reopen an issue, but there's a solution for [#47](https://github.com/ONLYOFFICE/onlyoffice-alfresco/issues/47)

The callback url isn't sent when mode=view. 
I forced it in the javascript and the problem is solved.

I suggest to update the Prepare.java in the repo to add callbackUrl for mode view.
I'll try to do a pull request for that.

**Comment by LinneyS** [comment]
The `callbackUrl` is not required in `mode=view`
You can install Document Server 5.5.1 or wait 5.5.4 to fix the [issue](https://github.com/ONLYOFFICE/DocumentServer/issues/914)

**Comment by svgta1** [comment]
The problem exist with 5.5.3 when an user open the document in view mode and an other user open it in editing mode view minutes after.
