### ISSUE TITLE
Add activity when creating doc and updating a doc

### ISSUE THREAD

**Issue by svgta1** [ONLYOFFICE/onlyoffice-alfresco#50]
The activity feed doesn't have the informations of creating a document with onlyoffice or updating it (new version) with onlyoffice to. It will be useful to add it in the repo Prepare.java when a document is created, and in the Backoffice.java when the document is updated.

The class org/alfresco/service/cmr/activities/ActivityPostService must be used for that.

**Comment by aleksandrfedorov97** [comment]
https://github.com/ONLYOFFICE/onlyoffice-alfresco/pull/141
