### ISSUE TITLE
onlyoffice:editing-hash

### ISSUE THREAD

**Issue by jmoest** [ONLYOFFICE/onlyoffice-alfresco#51]
Hello,
When user1 creates a new document or imports a new pdf and doesn't view the document.
User 2 has visitor authorization and displays the document via the document detail page.
The document is modified by User2 because a new property is added to the node: onlyoffice: edit-hash
Thank you
Jonathan

**Comment by svgta1** [comment]
That's right. And, I don't understand the reason to create a hash and not use the noderef.
But, if the document is viewed in readonly mod, the hash must not be created or changed. If it's not exist, the nodeRef could be used.
