### ISSUE TITLE
Double Edit in OnlyOffice buttons (4.2.0)

### ISSUE THREAD

**Issue by Radapompa** [ONLYOFFICE/onlyoffice-alfresco#61]
After upgrading to 4.2.0. There is now two Edit in OnlyOffice buttons. The first one works as intended. The second one goes to:
http://alfresco:8080/share/page/site/myTestSite/onlyoffice-edit?nodeRef={workingCopy.sourceNodeRef}

![bild](https://user-images.githubusercontent.com/8954878/93599997-4f233a80-f9bf-11ea-9f8f-cca9fd19d3f9.png)

**Comment by LinneyS** [comment]
Fixed at 45f86eb9cdeefa87ad4c820102608efab8f8e92e
Released on v4.3.0
