### ISSUE TITLE
Security hash verification failed

### ISSUE THREAD

**Issue by fredericmazzini** [ONLYOFFICE/onlyoffice-alfresco#67]
Hi,

We have migrated our Alfresco platform from Alfresco 5.0.4 with OnlyOffice plugin 2.0 to Alfresco 6.2.2 with OnlyOffice plugin 4.2.0.
Since, in our log files, we have a lot of errors : "Security hash verification failed" and our users lost their document modifications.

Could someone explain us how to resolve this problem ? It's extremely urgent.

Thank you four your help.

Best regards,

Fred

**Comment by alexanderonlyoffice** [comment]
@fredericmazzini, please refer to issue #40 in this branch. It might be that the reason of the issue is the same.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
