### ISSUE TITLE
Previsualization of TXT and CSV files fails

### ISSUE THREAD

**Issue by nandusmasta** [ONLYOFFICE/onlyoffice-alfresco#77]
Hey. First of all many thanks to the people behind awesome plugin! I am having a blast with it and are seriously considering adding it to our enterprise level alfresco solution. However there is one thing I found, that I couldn't manage or get around, which is the previsualization of CSV and TXT files. Whenever I try this with a file sample of those types(file-examples.com), OnlyOffice never seems to finish loading the document in the page. I am working with a 6.2 Alfresco installation and the latest OnlyOffice in different servers. Everything else works great but that. Do you guys know what could be the problem? Many thanks in advance.

**Comment by SergeyKorneyev** [comment]
Hello,
You should be able to open TXT and CSV files in view mode. Could you describe the way you try opening them step by step? Some screenshots or a video would also help

**Comment by nandusmasta** [comment]
Hey Sergei. Thanks for your quick reply! Here is a screenshot of the issue.

![image](https://user-images.githubusercontent.com/14926027/112140030-41d74a80-8bb2-11eb-8a69-8fe0f14d0811.png)

No error is given, the page just gets stuck in that state, with the onlyoffice section stuck in a "Loading..." state. It just never finishes. I tried again with a CSV file and this time it showed up, so I think the issue I have is only with TXT files.

**Comment by ShockwaveNN** [comment]
@nandusmasta Hi, not sure if this problem on connector, alfesco or DocumentServer side

I want to rule out DocumentServer side so please anwser some question

1. Exact DocumentServer version and server OS
2. Installation type (docker, deb, rpm or some other)
3. Is there any errors related to your files in `/var/log/onlyoffice`?

**Comment by nandusmasta** [comment]
Hi. Here are my answers:

1- Document Server 4.4.3.7 running on Ubuntu 18.04.3
2- Docker Installation
3- I took a snapshot of the container and under /var/log/onlyoffice there are no files. Am I missing some command to enable logging perhaps?

**Comment by ShockwaveNN** [comment]
> Document Server 4.4.3.7

To be clear - 4.4.3.7 is the version of DocumentServer inside a container?
This version was released 4 years ago and unsupported

You can attach to DocumentServer container via
```
dockere exec -it container_id bash
```

And run `dpkg -l | grep onlyoffice` command to get your version for sure

**Comment by nandusmasta** [comment]
Yes, the 4.4.3.7 version is running inside a container. Thanks for the attach tip. I ran it just in case and in fact it is that version. I am going to try to upgrade the OnlyOffice version, see if that solves the issue. Still, it is very strange that it only affects TXT files.

**Comment by ShockwaveNN** [comment]
@nandusmasta This version is VERY old so I think since them we may completly rewrite convert of txt files, but I'm not sure, a lot of changes happened in our project for 4 years

**Comment by nandusmasta** [comment]
@ShockwaveNN Yeah, 4 years ago is ancient times in IT. I was using it because our proxy/av was killing the pull command for the newer versions. I got in touch with our security department and managed to get an exception for pulling the 6.2 version. Now TXT file previews are working correctly. I am still going over everything we need, but that part is OK on my end. Sorry for the time invested on this, since it ended up being a simple "just upgrade" thing :)

**Comment by nandusmasta** [comment]
It was fixed by upgrading OO/DS from 4.4.3.7 to 6.2

**Comment by ShockwaveNN** [comment]
@nandusmasta Glad to hear
