### ISSUE TITLE
Error in Alfresco CE 201901GA

### ISSUE THREAD

**Issue by justemu** [ONLYOFFICE/onlyoffice-alfresco#9]
Environment:
alfresco CE version 201901GA(alfresco-content-repository-community:6.1.2-ga)
onlyoffice-alfresco add-on version 2.0.1
-------------------
Reproduction of Error:
Find a document and Edit in Onlyoffice...
Error shows up:

<img width="1128" alt="屏幕快照 2019-06-25 下午9 02 45" src="https://user-images.githubusercontent.com/20639347/60113489-71baa980-97a4-11e9-8fbd-e6e201603227.png">

The document could not be saved. Please check connection settings or contact your administrator.....
-----------------
I have set the address of alfresco in alfresco-global.properties according to the readme.
To rule out the possibility that the onlyoffice document server cannot get the right address of alfresco, I checked the log of alfresco and found a series error of "Access Denied"... indicating some deeper problems between this add-on and Alfresco CE 201901GA. When I remove this add-on from alfresco, error disapears.

Logs:
alfresco_1  |  2019-06-25 12:05:24,975  ERROR [extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-2] Exception from executeScript: 05250020 Access Denied.  You do not have the appropriate permissions to perform this operation.
alfresco_1  |  org.alfresco.repo.security.permissions.AccessDeniedException: 05250020 Access Denied.  You do not have the appropriate permissions to perform this operation.
alfresco_1  | 	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:57)
alfresco_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
alfresco_1  | 	at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:166)
alfresco_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
alfresco_1  | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
alfresco_1  | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
alfresco_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
alfresco_1  | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
alfresco_1  | 	at com.sun.proxy.$Proxy61.getWriter(Unknown Source)
alfresco_1  | 	at org.alfresco.repo.web.scripts.bean.ADMRemoteStore$5.doWork(ADMRemoteStore.java:595)
alfresco_1  | 	at org.alfresco.repo.web.scripts.bean.ADMRemoteStore$5.doWork(ADMRemoteStore.java:581)
alfresco_1  | 	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:623)
alfresco_1  | 	at org.alfresco.repo.web.scripts.bean.ADMRemoteStore.updateDocument(ADMRemoteStore.java:580)
alfresco_1  | 	at org.alfresco.repo.web.scripts.bean.BaseRemoteStore.execute(BaseRemoteStore.java:297)
alfresco_1  | 	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:512)
alfresco_1  | 	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
alfresco_1  | 	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
alfresco_1  | 	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
alfresco_1  | 	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
alfresco_1  | 	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
alfresco_1  | 	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
alfresco_1  | 	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
alfresco_1  | 	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
alfresco_1  | 	at org.alfresco.repo.web.scripts.AlfrescoWebScriptServlet.service(AlfrescoWebScriptServlet.java:43)
alfresco_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
alfresco_1  | 	at jdk.internal.reflect.GeneratedMethodAccessor465.invoke(Unknown Source)
alfresco_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:225)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
alfresco_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
alfresco_1  | 	at jdk.internal.reflect.GeneratedMethodAccessor456.invoke(Unknown Source)
alfresco_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
alfresco_1  | 	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
alfresco_1  | 	at jdk.internal.reflect.GeneratedMethodAccessor456.invoke(Unknown Source)
alfresco_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
alfresco_1  | 	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
alfresco_1  | 	at jdk.internal.reflect.GeneratedMethodAccessor456.invoke(Unknown Source)
alfresco_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
alfresco_1  | 	at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
alfresco_1  | 	at jdk.internal.reflect.GeneratedMethodAccessor456.invoke(Unknown Source)
alfresco_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
alfresco_1  | 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
alfresco_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
alfresco_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
alfresco_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
alfresco_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
alfresco_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
alfresco_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
alfresco_1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
alfresco_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
alfresco_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
alfresco_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
alfresco_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
alfresco_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
alfresco_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
alfresco_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
alfresco_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
alfresco_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
alfresco_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
alfresco_1  | 	at java.base/java.lang.Thread.run(Thread.java:834)
alfresco_1  | Caused by: net.sf.acegisecurity.AccessDeniedException: Access is denied.
alfresco_1  | 	at net.sf.acegisecurity.vote.AffirmativeBased.decide(AffirmativeBased.java:86)
alfresco_1  | 	at net.sf.acegisecurity.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:398)
alfresco_1  | 	at net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:77)
alfresco_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
alfresco_1  | 	at org.alfresco.repo.model.ml.MLContentInterceptor.invoke(MLContentInterceptor.java:136)
alfresco_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
alfresco_1  | 	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53)
alfresco_1  | 	... 120 more

**Comment by Eloncase** [comment]
Couldn't reproduce error. Can you please attach document server logs?

**Comment by justemu** [comment]
Hi Eloncase,

Here is the onlyoffice document server log, and I do find something wrong: 
The port 8080 in the log is not right for my alfresco server. It should be 99.
...
However, I have put the following lines in alfresco-global.properties.
`alfresco.host=a.touyan.net
alfresco.port=99
alfresco.protocol=https
alfresco.context=alfresco`

**How could onlyoffice document server still post data to port 8080?** 
Could you give me some hint to fix it? 

Many thanks!

---------
The following is the log...
---------
[2019-06-25T12:07:18.642] [ERROR] nodeJS - postData error: docId = d9266eb7-e85d-41fd-9819-6a2f54a7320b_20190624034840;url = https://a.touyan.net:8080/alfresco/s/parashift/onlyoffice/callback?nodeRef=workspace://SpacesStore/d9266eb7-e85d-41fd-9819-6a2f54a7320b&alf_ticket=TICKET_4f8f33635d8ed6f47c5ca5cfaa171d7000f8a9be;data = {"key":"d9266eb7-e85d-41fd-9819-6a2f54a7320b_20190624034840","status":1,"users":["bchen"],"actions":[{"type":1,"userid":"bchen"}]}
Error: write EPROTO 139664561854272:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
[2019-06-25T12:07:36.513] [ERROR] nodeJS - changesError: docId = d9266eb7-e85d-41fd-9819-6a2f54a7320b_20190624034840 Error: TypeError: undefined is not an object (evaluating 'this.mode.canDownload') Script: https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js Line: 40:7261 userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15 platform: MacIntel isLoadFullApi: true isDocumentLoadComplete: false StackTrace: show@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:40:7261
onBtnMenuToggle@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:40:14054
P@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:8:11044
https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:8:11242
https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:8:4446
c@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:11:13972
trigger@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:11:13229
toggle@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:23:17253
showMenu@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:40:17278
https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:42:12098
P@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:8:11044
https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:8:11242
https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:8:4446
i@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:13:26760
dispatch@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:10:7806
handle@https://h.chenb.cc:6481/v5.2.8-24/web-apps/apps/presentationeditor/main/app.js:10:5815
[2019-06-25T12:08:07.121] [ERROR] nodeJS - postData error: docId = e40ff9aa-ade4-4311-bfc3-0db4da74afcf_20190624144514;url = https://a.touyan.net:8080/alfresco/s/parashift/onlyoffice/callback?nodeRef=workspace://SpacesStore/e40ff9aa-ade4-4311-bfc3-0db4da74afcf&alf_ticket=TICKET_4f8f33635d8ed6f47c5ca5cfaa171d7000f8a9be;data = {"key":"e40ff9aa-ade4-4311-bfc3-0db4da74afcf_20190624144514","status":1,"users":["bchen"],"actions":[{"type":1,"userid":"bchen"}]}
Error: write EPROTO 139664561854272:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)

**Comment by Eloncase** [comment]
Make sure you don't overwrite those settings via environment variables.

Are you changing `alfresco-global.properties` file after you start alfresco? Alfresco doesn't reload settings on fly. Try to mount `alfresco-global.properties` file and start docker-compose that way:
```
services:
    alfresco:
        image: alfresco/alfresco-content-repository-community:6.1.2-ga
        volumes:
            - /alf/data/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
```

**Comment by justemu** [comment]
Thanks Eloncase, 
I find out the cause finally. It was in the docker-compose.yml file, where I set the port in java command line by "`-Dalfresco.port=8080`". And the java command line parameters have a higher priority than the` alfresco-global.properties.`
It was my fault and this is a false issue, which should be closed now.
